name: Playing with devbox

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install devbox
        uses: jetify-com/devbox-install-action@v0.11.0

      - name: Install warp
        run: devbox run warpinstall

      - name: Make the release and warp it
        run: devbox run -- rebar3 release

      - name: Start the release
        run: ./edenticon daemon

      - name: Ping the release
        run: ./edenticon ping

      - name: Use the release
        run: curl http://127.0.0.1:9091/generate/xxx?size=24

      - name: Stop the release
        run: ./edenticon stop
