name: Build and try an indenticon release

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install devbox
        uses: jetify-com/devbox-install-action@v0.11.0

      - name: Make the release and warp it
        run: devbox run -- rebar3 release

      - name: Start the release
        run: ./edenticon daemon

      - name: Ping the release
        run: ./edenticon ping

      - name: Default params
        run: curl http://127.0.0.1:9091/generate/xxx?size=24

      - name: Png and size
        run: curl http://127.0.0.1:9091/generate/xxx?size=24&format=png

      - name: SVG
        run: curl http://127.0.0.1:9091/generate/xxx?format=svg

      - name: Stop the release
        run: ./edenticon stop

      - name: Publish the release
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          source: edenticon.*
          target: public_html/edenticon/
